### PR TITLE
set last timer as new default

### LINKED ISSUE #9: Last timer
see https://twitter.com/simonharrer/status/1528480711648362497?s=20

### PR DESCRIPTION
**Pull request by hollesse**
fixes #9

### CODE REVIEW

**Comment by hollesse** [comment]
That was what I understood from his answer on twitter. Is that what you meant @simonharrer ?

**Comment by simonharrer** [comment]
No, it was simply a statement that there are two concepts. Would not merge this in this state. Last value and custom value are two different concepts, and I don’t think mixing them is good. We either support both or focus on one. I think the custom value is more valuable as I can set the typcial value (we rotate after 8inutes) nd sometimes deviate from that. i don’t want to lose my typical value because of the one deviation, having to type the custom value in again.

**Comment by gregorriegler** [comment]
Ok, what would be an example you liked better

**Comment by hollesse** [comment]
Should we then have an option to set default values for a room? But these would then be reset with every release. Or should we allow the users to set their default and save it in their local storage?

**Comment by simonharrer** [comment]
Again, not easy because some people create new rooms per feature whereas some always stay in their specific room. Habing a default value for a room is only helpful for a team that doesn’t change the room, and without persistence storage it just doesn’t work.

**Comment by gregorriegler** [comment]
@simonharrer one question: what is that special occasion, when you want to change the timer? Do you have an example?
I'm asking because it sounds like what you want is more time, which a "Pause Button" could also solve.

**Comment by simonharrer** [comment]
Examples: 

- Let's time box this and come back in 30 minutes.
- We talked so much, let's extend the timer by 5 more minutes.
- We forgot to start the timer, let's just say 5 minutes and then we switch.

**Comment by hollesse** [comment]
As I understand your points it then could be a solution to alle the user to set his/her default value for the timer. The the user can use this timer regularly and if they need another timer use the drop-down. But that would not solve the need for custom timers. For that we could also add user specific settings

**Comment by simonharrer** [comment]
> As I understand your points it then could be a solution to alle the user to set his/her default value for the timer. The the user can use this timer regularly and if they need another timer use the drop-down. 

That is the currently implemented solution, with the "default" value configured on the web and stored in localStorage per user.

> But that would not solve the need for custom timers. For that we could also add user specific settings

The question is: is there really a need for that? I haven't had that need in my coachings.

**Comment by simonharrer** [comment]
Cool idea, but most people use the CLI anyway, so would be a huge invest for a feature only very very few people will use.

**Pull request closed without merging**
